# Generated by Django 6.0.7 on 2026-07-24 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='コード')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='領域名')),
            ],
            options={
                'verbose_name': '領域',
                'verbose_name_plural': '領域',
            },
        ),
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='保管場所名')),
            ],
            options={
                'verbose_name': '保管場所',
                'verbose_name_plural': '保管場所',
            },
        ),
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='種別名')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kinds', to='equipment.area', verbose_name='領域')),
            ],
            options={
                'verbose_name': '種別',
                'verbose_name_plural': '種別',
                'unique_together': {('area', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('management_code', models.CharField(max_length=10, unique=True, verbose_name='品目コード')),
                ('model_name', models.CharField(max_length=200, verbose_name='機種')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='名称')),
                ('notes', models.TextField(blank=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipments', to='equipment.area', verbose_name='領域')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipments', to='equipment.kind', verbose_name='種別')),
                ('storage_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipments', to='equipment.storagelocation', verbose_name='保管場所')),
            ],
            options={
                'verbose_name': '機材',
                'verbose_name_plural': '機材',
                'ordering': ['management_code'],
            },
        ),
    ]
