# Generated by Django 6.0.7 on 2026-08-24 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='削除済み'),
        ),
        migrations.CreateModel(
            name='EquipmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', '登録'), ('update', '変更'), ('delete', '削除'), ('restore', '復元')], max_length=10, verbose_name='操作')),
                ('changes', models.TextField(blank=True, verbose_name='変更内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作日時')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='equipment.equipment', verbose_name='機材')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作者')),
            ],
            options={
                'verbose_name': '変更履歴',
                'verbose_name_plural': '変更履歴',
                'ordering': ['-created_at'],
            },
        ),
    ]
