# Generated by Django 6.0.7 on 2026-08-25 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_equipment_is_deleted_equipmenthistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['code'], 'verbose_name': '領域', 'verbose_name_plural': '領域'},
        ),
        migrations.AlterModelOptions(
            name='kind',
            options={'ordering': ['area__code', 'sort_order', 'name'], 'verbose_name': '種別', 'verbose_name_plural': '種別'},
        ),
        migrations.AddField(
            model_name='kind',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='表示順'),
        ),
    ]
