# Generated by Django 6.0.7 on 2026-08-26 02:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_alter_area_options_alter_kind_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='案件名')),
                ('loan_date', models.DateField(verbose_name='貸出日')),
                ('return_date', models.DateField(verbose_name='返却予定日')),
                ('notes', models.TextField(blank=True, verbose_name='備考')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除済み')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='担当者')),
            ],
            options={
                'verbose_name': '案件',
                'verbose_name_plural': '案件',
                'ordering': ['-loan_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('checked_out_at', models.DateTimeField(blank=True, null=True, verbose_name='出庫日時')),
                ('returned_at', models.DateTimeField(blank=True, null=True, verbose_name='返却日時')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_assignments', to=settings.AUTH_USER_MODEL, verbose_name='登録者')),
                ('checked_out_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_out_assignments', to=settings.AUTH_USER_MODEL, verbose_name='出庫処理者')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='equipment.equipment', verbose_name='機材')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='equipment.project', verbose_name='案件')),
                ('returned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returned_assignments', to=settings.AUTH_USER_MODEL, verbose_name='返却処理者')),
            ],
            options={
                'verbose_name': '案件機材',
                'verbose_name_plural': '案件機材',
                'ordering': ['equipment__management_code'],
                'unique_together': {('project', 'equipment')},
            },
        ),
    ]
