from django.urls import path
from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("list/", views.equipment_list, name="equipment_list"),
    path("gantt/", views.equipment_gantt, name="equipment_gantt"),    
    path("create/", views.equipment_create, name="equipment_create"),
    path("print/", views.equipment_print, name="equipment_print"),
    path("csv/", views.equipment_csv, name="equipment_csv"),
    path("label-csv/", views.equipment_label_csv, name="equipment_label_csv"),
    path("<int:pk>/edit/", views.equipment_update, name="equipment_update"),
    path("<int:pk>/delete/", views.equipment_delete, name="equipment_delete"),
    path("<int:pk>/restore/", views.equipment_restore, name="equipment_restore"),
    path("<int:pk>/history/", views.equipment_history, name="equipment_history"),
    path("users/", views.user_list, name="user_list"),
    path("users/create/", views.user_create, name="user_create"),
    path("users/<int:pk>/edit/", views.user_update, name="user_update"),
    path("users/<int:pk>/password/", views.user_password, name="user_password"),
    path("history/", views.history_list, name="history_list"),
    path("projects/", views.project_list, name="project_list"),
    path("projects/create/", views.project_create, name="project_create"),
    path("projects/<int:pk>/", views.project_detail, name="project_detail"),
    path("projects/<int:pk>/edit/", views.project_update, name="project_update"),
    path("projects/<int:pk>/delete/", views.project_delete, name="project_delete"),
    path("projects/<int:pk>/restore/", views.project_restore, name="project_restore"),
    path("projects/<int:pk>/add-equipment/", views.project_add_equipment, name="project_add_equipment"),
    path("projects/<int:pk>/print/", views.project_print, name="project_print"),     
    path("loan/", views.loan_project_list, name="loan_project_list"),
    path("loan/<int:pk>/", views.loan_scan, name="loan_scan"),
    path("return/", views.return_project_list, name="return_project_list"),
    path("return/<int:pk>/", views.return_scan, name="return_scan"),
    path("api/next-code/", views.next_code_api, name="next_code_api"),
    path("api/models/", views.model_list_api, name="model_list_api"),    
    path("<int:pk>/usage/", views.equipment_usage, name="equipment_usage"),    
]